### ISSUE TITLE
Bug in reduce labels to spots

### ISSUE THREAD

**Issue by ofrag** [clij/clijx#26]
Hi,

I find both CLIJx_reduceLabelsToLabelledSpots  and CLIJx_extendLabelsWithMaximumRadius usefull and would like to see them in the official release. 

CLIJx_reduceLabelsToLabelledSpots has a bug, it replaces each label N with a spot with a value of N-1 , thus removing label #1.
It also adds a spot with value MaxN at the top left corner of the first slice of the image. 
Sample file and output can be found [here](https://www.dropbox.com/sh/m1kuqs4cf11rgz0/AAAaS4sytj0ipCswSKwMVxw8a?dl=0)

Thanks
Ofra

**Comment by haesleinhuepf** [comment]
Hey @ofrag ,

good catch! Thanks for reporting this bug! I'll cut a release this week and then you should be able to use it.
