### ISSUE TITLE
Correction in non_local_means_Xd_x.cl : Pixel value p1 is read from the wrong source

### ISSUE THREAD

**Issue by iwbh15** [clij/clijx#44]
In the 2D and 3D version of non_local_means_Xd_x.cl the pixel value p1 is read from the wrong source.

p1 is local mean of current position and can be read outside of the loop.

```
     double p1 = (double)(READ_IMAGE(input, sampler,      (int4)(i+i2,j+j2,k+k2,0)).x);
     double p2 = (double)(READ_IMAGE(local_mean, sampler, (int4)(i+i2,j+j2,k+k2,0)).x);
```
should be changed in the *.cl files to:

```
     double p1 = (double)(READ_IMAGE(local_mean, sampler,      (int2)(i,j,k,0)).x);
     double p2 = (double)(READ_IMAGE(local_mean, sampler, (int4)(i+i2,j+j2,k+k2,0)).x);

```
see:
https://forum.image.sc/t/clij2-non-local-means-cpu-vs-gpu-results/53772/22?u=phaub

Here are two corrected files:
[non_local_means_ModifiedFiles.zip](https://github.com/clij/clijx/files/9092176/non_local_means_ModifiedFiles.zip)

**Comment by haesleinhuepf** [comment]
Hi @iwbh15 ,

amazing, thanks! Do you want to send this as pull-request?

Thanks!

Best,
Robert

**Comment by iwbh15** [comment]
Sorry @haesleinhuepf,
my clijx fork is totally outdated and I can not create a PR with a few steps.

**Comment by haesleinhuepf** [comment]
Ok, no problem @iwbh15 . I just updated clijx and version 0.32.2.0 contains your proposal. Let me know if it works!

Thanks again!

Best,
Robert

**Comment by iwbh15** [comment]
The correction in 0.32.2.0 works as expected.
Peter
